<style>
  body {
    background-color: #f8f9fa;
    color: #343a40;
    font-family: 'Arial', sans-serif;
  }

  .header {
    background-color: #0366d6;
    color: #ffffff;
    padding: 20px;
    text-align: center;
  }

  h1, h2, h3, h4, h5, h6 {
    color: #0366d6;
  }

  .footer {
    background-color: #24292e;
    color: #ffffff;
    padding: 10px;
    text-align: center;
    position: fixed;
    bottom: 0;
    width: 100%;
  }
</style>
